package es.boe.controlpublicacion;

import javax.annotation.Resource;
import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;

import es.boe.controlpublicacion.contexto.ContextoLlamada;
import es.boe.controlpublicacion.exceptions.ControlPublicacionException;
import es.boe.controlpublicacion.utils.Constantes;
import es.tributasenasturias.utils.log.Logger;

/**
 * La url del servicio debe indicarse en el XML de envio de los anuncios dentro
 * del elemento <urlSw> en el apartado <metadatos
 * 
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "ServicioControlPublicacionPublicacionPort", serviceName = "ServicioControlPublicacionBOE", targetNamespace = "http://www.boe.es/ServicioControlPublicacion", wsdlLocation = "/wsdls/ServicioControlPublicacion-v1.0.wsdl", endpointInterface = "es.boe.controlpublicacion.ServicioControlPublicacion")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain(file="HandlerChain.xml")
public class ServicioControlPublicacionBOE_ServicioControlPublicacionPublicacionPortImpl
		implements ServicioControlPublicacion {

	public ServicioControlPublicacionBOE_ServicioControlPublicacionPublicacionPortImpl() {
	}

	@Resource
	 WebServiceContext wsc;
	/**
	 * Operacion que deben implementar los organos emisores de anuncios para
	 * recibir informacion acerca de la publicacion de sus anuncio
	 * 
	 * @param publicacion XMl de publicación en base64
	 * @return returns es.boe.controlpublicacion.Respuesta
	 */
	public Respuesta controlPublicacion(String publicacion) {
		Respuesta respuesta = new Respuesta();
		ContextoLlamada contexto;
		Logger log=null;
		try
		{
			contexto = (ContextoLlamada) wsc.getMessageContext().get(Constantes.CONTEXTO);
			if (contexto==null)
			{
				throw new ControlPublicacionException("Error, se ha recibido un contexto de llamada nulo.");
			}
			log = contexto.getLogger();
			return new ControlPublicacionImpl(contexto).controlPublicacion(publicacion);
			
		}
		catch (Exception e)
		{
			if (log!=null)
			{
				log.error("Error en el servicio de control de publicación:"+ e.getMessage());
				log.trace(e.getStackTrace());
			}
			respuesta.setCodigo(Constantes.ERROR_TECNICO_CODE);
			respuesta.setDescripcion(Constantes.ERROR_TECNICO_MSG);
			return respuesta;
		}
	}

}
