//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.19 at 01:53:28 PM CEST 
//


package es.boe.controlpublicacion.tipos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Informacion de un anuncio
 * 
 * <p>Java class for Anuncio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Anuncio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idEnvio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idBoe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cve" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="urlBoe" type="{http://www.boe.es/ControlPublicacion}UrlBoe"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Anuncio", propOrder = {
    "idEnvio",
    "idBoe",
    "cve",
    "urlBoe"
})
public class Anuncio {

    @XmlElement(required = true)
    protected String idEnvio;
    @XmlElement(required = true)
    protected String idBoe;
    @XmlElement(required = true)
    protected String cve;
    @XmlElement(required = true)
    protected UrlBoe urlBoe;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the idEnvio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdEnvio() {
        return idEnvio;
    }

    /**
     * Sets the value of the idEnvio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdEnvio(String value) {
        this.idEnvio = value;
    }

    /**
     * Gets the value of the idBoe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdBoe() {
        return idBoe;
    }

    /**
     * Sets the value of the idBoe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdBoe(String value) {
        this.idBoe = value;
    }

    /**
     * Gets the value of the cve property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCve() {
        return cve;
    }

    /**
     * Sets the value of the cve property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCve(String value) {
        this.cve = value;
    }

    /**
     * Gets the value of the urlBoe property.
     * 
     * @return
     *     possible object is
     *     {@link UrlBoe }
     *     
     */
    public UrlBoe getUrlBoe() {
        return urlBoe;
    }

    /**
     * Sets the value of the urlBoe property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrlBoe }
     *     
     */
    public void setUrlBoe(UrlBoe value) {
        this.urlBoe = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
