//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.19 at 01:53:28 PM CEST 
//


package es.boe.controlpublicacion.tipos;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.boe.controlpublicacion.tipos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Publicacion_QNAME = new QName("http://www.boe.es/ControlPublicacion", "publicacion");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.boe.controlpublicacion.tipos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListaAnuncios }
     * 
     */
    public ListaAnuncios createListaAnuncios() {
        return new ListaAnuncios();
    }

    /**
     * Create an instance of {@link Publicacion }
     * 
     */
    public Publicacion createPublicacion() {
        return new Publicacion();
    }

    /**
     * Create an instance of {@link Anuncio }
     * 
     */
    public Anuncio createAnuncio() {
        return new Anuncio();
    }

    /**
     * Create an instance of {@link UrlBoe }
     * 
     */
    public UrlBoe createUrlBoe() {
        return new UrlBoe();
    }

    /**
     * Create an instance of {@link Fecha }
     * 
     */
    public Fecha createFecha() {
        return new Fecha();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Publicacion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.boe.es/ControlPublicacion", name = "publicacion")
    public JAXBElement<Publicacion> createPublicacion(Publicacion value) {
        return new JAXBElement<Publicacion>(_Publicacion_QNAME, Publicacion.class, null, value);
    }

}
