//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.19 at 01:53:28 PM CEST 
//


package es.boe.controlpublicacion.tipos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Informacion de publicacion de anuncios
 * 
 * <p>Java class for Publicacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Publicacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fecha" type="{http://www.boe.es/ControlPublicacion}Fecha"/>
 *         &lt;element name="anuncios" type="{http://www.boe.es/ControlPublicacion}ListaAnuncios"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Publicacion", propOrder = {
    "fecha",
    "anuncios"
})
public class Publicacion {

    @XmlElement(required = true)
    protected Fecha fecha;
    @XmlElement(required = true)
    protected ListaAnuncios anuncios;

    /**
     * Gets the value of the fecha property.
     * 
     * @return
     *     possible object is
     *     {@link Fecha }
     *     
     */
    public Fecha getFecha() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fecha }
     *     
     */
    public void setFecha(Fecha value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the anuncios property.
     * 
     * @return
     *     possible object is
     *     {@link ListaAnuncios }
     *     
     */
    public ListaAnuncios getAnuncios() {
        return anuncios;
    }

    /**
     * Sets the value of the anuncios property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaAnuncios }
     *     
     */
    public void setAnuncios(ListaAnuncios value) {
        this.anuncios = value;
    }

}
